### ISSUE TITLE
piwik.js not found

### ISSUE THREAD

**Issue by sarkrui** [holehan/hugo-component-matomo#9]
Hi Holehan, 

Is this an abnormal error? I have nowhere to find this script in the repository. 

### Configuration
- hugo v0.86.0+extended darwin/arm64
- using papermod theme 
- {{ partial "matomo-tracking" . }} is referenced in `layout/partials/extend_footer.html` (as [suggested](https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#custom-head--footer) by the papermod theme)

```yaml
theme: 
  - "PaperMod"
  - "matomo"

matomo:
    url: https://analytics.domain.com // as exact as my self-held matomo server
    id: 1
    disableSRI: false 
```

**Console log**
```
/piwik.js net::ERR_ABORTED 404
```
